package co.q64.dynamicalsystems.material;

import co.q64.dynamicalsystems.material.materials.elements.AluminiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.AmericiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.AntimonyMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ArgonMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ArsenicMaterial;
import co.q64.dynamicalsystems.material.materials.elements.BariumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.BerylliumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.BismuthMaterial;
import co.q64.dynamicalsystems.material.materials.elements.BoronMaterial;
import co.q64.dynamicalsystems.material.materials.elements.CadmiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.CaesiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.CalciumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.CarbonMaterial;
import co.q64.dynamicalsystems.material.materials.elements.CeriumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ChlorineMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ChromeMaterial;
import co.q64.dynamicalsystems.material.materials.elements.CobaltMaterial;
import co.q64.dynamicalsystems.material.materials.elements.CopperMaterial;
import co.q64.dynamicalsystems.material.materials.elements.DysprosiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ErbiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.EuropiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.FluorineMaterial;
import co.q64.dynamicalsystems.material.materials.elements.GadoliniumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.GalliumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.GoldMaterial;
import co.q64.dynamicalsystems.material.materials.elements.HeliumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.HolmiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.HydrogenMaterial;
import co.q64.dynamicalsystems.material.materials.elements.IndiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.IridiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.IronMaterial;
import co.q64.dynamicalsystems.material.materials.elements.LanthanumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.LeadMaterial;
import co.q64.dynamicalsystems.material.materials.elements.LithiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.LutetiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.MagnesiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ManganeseMaterial;
import co.q64.dynamicalsystems.material.materials.elements.MercuryMaterial;
import co.q64.dynamicalsystems.material.materials.elements.MolybdenumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.NeodymiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.NickelMaterial;
import co.q64.dynamicalsystems.material.materials.elements.NiobiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.NitrogenMaterial;
import co.q64.dynamicalsystems.material.materials.elements.OsmiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.OxygenMaterial;
import co.q64.dynamicalsystems.material.materials.elements.PalladiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.PhosphorusMaterial;
import co.q64.dynamicalsystems.material.materials.elements.PlatinumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.PlutoniumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.PotassiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.PraseodymiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.PromethiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.RadonMaterial;
import co.q64.dynamicalsystems.material.materials.elements.RubidiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.SamariumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ScandiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.SiliconMaterial;
import co.q64.dynamicalsystems.material.materials.elements.SilverMaterial;
import co.q64.dynamicalsystems.material.materials.elements.SodiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.StrontiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.SulfurMaterial;
import co.q64.dynamicalsystems.material.materials.elements.TantalumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.TelluriumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.TerbiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ThoriumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ThuliumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.TinMaterial;
import co.q64.dynamicalsystems.material.materials.elements.TitaniumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.TungstenMaterial;
import co.q64.dynamicalsystems.material.materials.elements.UraniumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.VanadiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.YtterbiumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.YttriumMaterial;
import co.q64.dynamicalsystems.material.materials.elements.ZincMaterial;

import javax.inject.Inject;
import javax.inject.Singleton;

@Singleton
public class Materials {

    // Elements
    public @Inject AluminiumMaterial aluminium;
    public @Inject AmericiumMaterial americium;
    public @Inject AntimonyMaterial antimony;
    public @Inject ArgonMaterial argon;
    public @Inject ArsenicMaterial arsenic;
    public @Inject BariumMaterial barium;
    public @Inject BerylliumMaterial beryllium;
    public @Inject BismuthMaterial bismuth;
    public @Inject BoronMaterial boron;
    public @Inject CaesiumMaterial caesium;
    public @Inject CalciumMaterial calcium;
    public @Inject CarbonMaterial carbon;
    public @Inject CadmiumMaterial cadmium;
    public @Inject CeriumMaterial cerium;
    public @Inject ChlorineMaterial chlorine;
    public @Inject ChromeMaterial chrome;
    public @Inject CobaltMaterial cobalt;
    public @Inject CopperMaterial copper;
    public @Inject DysprosiumMaterial dysprosium;
    public @Inject ErbiumMaterial erbium;
    public @Inject EuropiumMaterial europium;
    public @Inject FluorineMaterial fluorine;
    public @Inject GadoliniumMaterial gadolinium;
    public @Inject GalliumMaterial gallium;
    public @Inject GoldMaterial gold;
    public @Inject HolmiumMaterial holmium;
    public @Inject HydrogenMaterial hydrogen;
    public @Inject HeliumMaterial helium;
    public @Inject IndiumMaterial indium;
    public @Inject IridiumMaterial iridium;
    public @Inject IronMaterial iron;
    public @Inject LanthanumMaterial lanthanum;
    public @Inject LeadMaterial lead;
    public @Inject LithiumMaterial lithium;
    public @Inject LutetiumMaterial lutetium;
    public @Inject MagnesiumMaterial magnesium;
    public @Inject ManganeseMaterial manganese;
    public @Inject MercuryMaterial mercury;
    public @Inject MolybdenumMaterial molybdenum;
    public @Inject NeodymiumMaterial neodymium;
    public @Inject NickelMaterial nickel;
    public @Inject NiobiumMaterial niobium;
    public @Inject NitrogenMaterial nitrogen;
    public @Inject OsmiumMaterial osmium;
    public @Inject OxygenMaterial oxygen;
    public @Inject PalladiumMaterial palladium;
    public @Inject PhosphorusMaterial phosphorus;
    public @Inject PlatinumMaterial platinum;
    public @Inject PlutoniumMaterial plutonium;
    public @Inject PotassiumMaterial potassium;
    public @Inject PraseodymiumMaterial praseodymium;
    public @Inject PromethiumMaterial promethium;
    public @Inject RadonMaterial radon;
    public @Inject RubidiumMaterial rubidium;
    public @Inject SamariumMaterial samarium;
    public @Inject ScandiumMaterial scandium;
    public @Inject SiliconMaterial silicon;
    public @Inject SilverMaterial silver;
    public @Inject SodiumMaterial sodium;
    public @Inject StrontiumMaterial strontium;
    public @Inject SulfurMaterial sulfur;
    public @Inject TantalumMaterial tantalum;
    public @Inject TelluriumMaterial tellurium;
    public @Inject TerbiumMaterial terbium;
    public @Inject ThoriumMaterial thorium;
    public @Inject ThuliumMaterial thulium;
    public @Inject TinMaterial tin;
    public @Inject TitaniumMaterial titanium;
    public @Inject TungstenMaterial tungsten;
    public @Inject UraniumMaterial uranium;
    public @Inject VanadiumMaterial vanadium;
    public @Inject YttriumMaterial yttrium;
    public @Inject YtterbiumMaterial ytterbium;
    public @Inject ZincMaterial zinc;

    protected @Inject Materials() {}

}
